# Title: m-120.yaml
# Author: Dae-Cheol, Noh
# Date: 2021-04-06 15:24

backbone: 'yolov5_lite'

#########################################################
hyp:  # hyp.scratch.yaml 
  lr0: 0.01  # initial learning rate (SGD=1E-2, Adam=1E-3)
  lrf: 0.2  # final OneCycleLR learning rate (lr0 * lrf)
  momentum: 0.937  # SGD momentum/Adam beta1
  weight_decay: 0.0005  # optimizer weight decay 5e-4
  warmup_epochs: 3.0  # warmup epochs (fractions ok)
  warmup_momentum: 0.8  # warmup initial momentum
  warmup_bias_lr: 0.1  # warmup initial bias lr
  box: 0.05  # box loss gain
  cls: 0.5  # cls loss gain
  cls_pw: 1.0  # cls BCELoss positive_weight
  obj: 1.0  # obj loss gain (scale with pixels)
  obj_pw: 1.0  # obj BCELoss positive_weight
  iou_t: 0.20  # IoU training threshold
  anchor_t: 4.0  # anchor-multiple threshold
  # anchors: 3  # anchors per output layer (0 to ignore)
  fl_gamma: 0.0  # focal loss gamma (efficientDet default gamma=1.5)
  hsv_h: 0.015  # image HSV-Hue augmentation (fraction)
  hsv_s: 0.7  # image HSV-Saturation augmentation (fraction)
  hsv_v: 0.4  # image HSV-Value augmentation (fraction)
  degrees: 0.0  # image rotation (+/- deg)
  translate: 0.1  # image translation (+/- fraction)
  scale: 0.5  # image scale (+/- gain)
  shear: 0.0  # image shear (+/- deg)
  perspective: 0.0  # image perspective (+/- fraction), range 0-0.001
  flipud: 0.0  # image flip up-down (probability)
  fliplr: 0.5  # image flip left-right (probability)
  mosaic: 1.0  # image mosaic (probability)
  mixup: 0.0  # image mixup (probability)

#########################################################
train:    # train.py
  weights: 'yolov5m.pt'    # modify here
  cfg: 'yolov5m.yaml'    # modify here
  data: 'data.yaml'    # modify here
  epochs: 300    # modify here
  batch_size: 16    # modify here
  img_size: [640, 640]    # [train_size, test_size]
  rect: False
  resume: False
  nosave: False
  notest: False
  noautoanchor: False
  evolve: False
  bucket: ''
  cache_images: False
  image_weights: False
  device: 0
  multi_scale: False
  single_cls: False
  adam: False
  sync_bn: False
  local_rank: -1
  workers: 8
  project: ''    # modify here
  entity: None
  name: 'exp'
  exist_ok: False
  quad: False
  linear_lr: False
  label_smoothing: 0.0
  upload_dataset: False
  bbox_interval: -1
  save_period: -1
  artifact_alias: 'latest'

#########################################################
valid:    # test.py
  weights: 'yolov5m.pt'    # modify here
  data: 'data.yaml'    # modify here
  batch_size: 32    # modify here
  img_size: 640
  conf_thres: 0.001
  iou_thres: 0.6
  task: 'val'
  device: 0
  single_cls: False
  augment: False
  verbose: False
  save_txt: False
  save_hybrid: False
  save_conf: False
  save_json: False
  project: ''    # modify here
  name: 'exp'
  exist_ok: False

#########################################################
test:   # detect.py
  weights: 'yolov5m.pt'    # modify here
  source: '/path/to/images'
  img_size: 640
  conf_thres: 0.25
  iou_thres: 0.45
  device: 0
  view_img: False
  save_txt: False
  save_conf: False
  nosave: False
  classes: None
  agnostic_nms: False
  augment: False
  update: False
  project: ''
  name: 'exp'
  exist_ok: False

#########################################################
model:  # yolov5m.yaml
  yolov5s:
    nc: 1      # modify here -> number of classes
    classes: ['nothing']    # modify here -> name of classes

    depth_multiple: 0.33  # model depth multiple
    width_multiple: 0.50  # layer channel multiple

    anchors:
      - [10,13, 16,30, 33,23]  # P3/8
      - [30,61, 62,45, 59,119]  # P4/16
      - [116,90, 156,198, 373,326]  # P5/32

    # YOLOv5 backbone
    backbone:
      # [from, number, module, args]
      [[-1, 1, Focus, [64, 3]],  # 0-P1/2
      [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
      [-1, 3, C3, [128]],
      [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
      [-1, 9, C3, [256]],
      [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
      [-1, 9, C3, [512]],
      [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
      [-1, 1, SPP, [1024, [5, 9, 13]]],
      [-1, 3, C3, [1024, False]],  # 9
      ]

    # YOLOv5 head
    head:
      [[-1, 1, Conv, [512, 1, 1]],
      [-1, 1, nn.Upsample, [None, 2, 'nearest']],
      [[-1, 6], 1, Concat, [1]],  # cat backbone P4
      [-1, 3, C3, [512, False]],  # 13

      [-1, 1, Conv, [256, 1, 1]],
      [-1, 1, nn.Upsample, [None, 2, 'nearest']],
      [[-1, 4], 1, Concat, [1]],  # cat backbone P3
      [-1, 3, C3, [256, False]],  # 17 (P3/8-small)

      [-1, 1, Conv, [256, 3, 2]],
      [[-1, 14], 1, Concat, [1]],  # cat head P4
      [-1, 3, C3, [512, False]],  # 20 (P4/16-medium)

      [-1, 1, Conv, [512, 3, 2]],
      [[-1, 10], 1, Concat, [1]],  # cat head P5
      [-1, 3, C3, [1024, False]],  # 23 (P5/32-large)

      [[17, 20, 23], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
      ]

  yolov5m:
    nc: 1      # modify here -> number of classes
    classes: ['nothing']    # modify here -> name of classes

    # DO NOT MODIFY HERE ##########################################
    depth_multiple: 0.67  # model depth multiple
    width_multiple: 0.75  # layer channel multiple

    # anchors
    anchors:
      - [10,13, 16,30, 33,23]  # P3/8
      - [30,61, 62,45, 59,119]  # P4/16
      - [116,90, 156,198, 373,326]  # P5/32

    # YOLOv5 backbone
    backbone:
      # [from, number, module, args]
      [[-1, 1, Focus, [64, 3]],  # 0-P1/2
      [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
      [-1, 3, C3, [128]],
      [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
      [-1, 9, C3, [256]],
      [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
      [-1, 9, C3, [512]],
      [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
      [-1, 1, SPP, [1024, [5, 9, 13]]],
      [-1, 3, C3, [1024, False]],  # 9
      ]

    # YOLOv5 head
    head:
      [[-1, 1, Conv, [512, 1, 1]],
      [-1, 1, nn.Upsample, [None, 2, 'nearest']],
      [[-1, 6], 1, Concat, [1]],  # cat backbone P4
      [-1, 3, C3, [512, False]],  # 13

      [-1, 1, Conv, [256, 1, 1]],
      [-1, 1, nn.Upsample, [None, 2, 'nearest']],
      [[-1, 4], 1, Concat, [1]],  # cat backbone P3
      [-1, 3, C3, [256, False]],  # 17 (P3/8-small)

      [-1, 1, Conv, [256, 3, 2]],
      [[-1, 14], 1, Concat, [1]],  # cat head P4
      [-1, 3, C3, [512, False]],  # 20 (P4/16-medium)

      [-1, 1, Conv, [512, 3, 2]],
      [[-1, 10], 1, Concat, [1]],  # cat head P5
      [-1, 3, C3, [1024, False]],  # 23 (P5/32-large)

      [[17, 20, 23], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
      ]

  yolov5l:
    nc: 1      # modify here -> number of classes
    classes: ['nothing']    # modify here -> name of classes

    depth_multiple: 1.0  # model depth multiple
    width_multiple: 1.0  # layer channel multiple

    anchors:
      - [10,13, 16,30, 33,23]  # P3/8
      - [30,61, 62,45, 59,119]  # P4/16
      - [116,90, 156,198, 373,326]  # P5/32

    # YOLOv5 backbone
    backbone:
      # [from, number, module, args]
      [[-1, 1, Focus, [64, 3]],  # 0-P1/2
      [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
      [-1, 3, C3, [128]],
      [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
      [-1, 9, C3, [256]],
      [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
      [-1, 9, C3, [512]],
      [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
      [-1, 1, SPP, [1024, [5, 9, 13]]],
      [-1, 3, C3, [1024, False]],  # 9
      ]

    # YOLOv5 head
    head:
      [[-1, 1, Conv, [512, 1, 1]],
      [-1, 1, nn.Upsample, [None, 2, 'nearest']],
      [[-1, 6], 1, Concat, [1]],  # cat backbone P4
      [-1, 3, C3, [512, False]],  # 13

      [-1, 1, Conv, [256, 1, 1]],
      [-1, 1, nn.Upsample, [None, 2, 'nearest']],
      [[-1, 4], 1, Concat, [1]],  # cat backbone P3
      [-1, 3, C3, [256, False]],  # 17 (P3/8-small)

      [-1, 1, Conv, [256, 3, 2]],
      [[-1, 14], 1, Concat, [1]],  # cat head P4
      [-1, 3, C3, [512, False]],  # 20 (P4/16-medium)

      [-1, 1, Conv, [512, 3, 2]],
      [[-1, 10], 1, Concat, [1]],  # cat head P5
      [-1, 3, C3, [1024, False]],  # 23 (P5/32-large)

      [[17, 20, 23], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
      ]

  yolov5x:
    nc: 1  # number of classes
    classes: ['nothing']    # modify here -> name of classes

    depth_multiple: 1.33  # model depth multiple
    width_multiple: 1.25  # layer channel multiple

    anchors:
      - [10,13, 16,30, 33,23]  # P3/8
      - [30,61, 62,45, 59,119]  # P4/16
      - [116,90, 156,198, 373,326]  # P5/32

    # YOLOv5 backbone
    backbone:
      # [from, number, module, args]
      [[-1, 1, Focus, [64, 3]],  # 0-P1/2
      [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
      [-1, 3, C3, [128]],
      [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
      [-1, 9, C3, [256]],
      [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
      [-1, 9, C3, [512]],
      [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
      [-1, 1, SPP, [1024, [5, 9, 13]]],
      [-1, 3, C3, [1024, False]],  # 9
      ]

    # YOLOv5 head
    head:
      [[-1, 1, Conv, [512, 1, 1]],
      [-1, 1, nn.Upsample, [None, 2, 'nearest']],
      [[-1, 6], 1, Concat, [1]],  # cat backbone P4
      [-1, 3, C3, [512, False]],  # 13

      [-1, 1, Conv, [256, 1, 1]],
      [-1, 1, nn.Upsample, [None, 2, 'nearest']],
      [[-1, 4], 1, Concat, [1]],  # cat backbone P3
      [-1, 3, C3, [256, False]],  # 17 (P3/8-small)

      [-1, 1, Conv, [256, 3, 2]],
      [[-1, 14], 1, Concat, [1]],  # cat head P4
      [-1, 3, C3, [512, False]],  # 20 (P4/16-medium)

      [-1, 1, Conv, [512, 3, 2]],
      [[-1, 10], 1, Concat, [1]],  # cat head P5
      [-1, 3, C3, [1024, False]],  # 23 (P5/32-large)

      [[17, 20, 23], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
      ]

  yolov5_lite:
    nc: 1  # number of classes
    classes: ['nothing']    # modify here -> name of classes

    depth_multiple: 1.0  # model depth multiple
    width_multiple: 1.0  # layer channel multiple

    # anchors
    anchors:
      - [ 4,5,  8,10,  13,16 ]  # P3/8
      - [ 23,29,  43,55,  73,105 ]  # P4/16
      - [ 146,217,  231,300,  335,433 ]  # P5/32

    # custom backbone
    backbone:
      # [from, number, module, args]
      [ [ -1, 1, conv_bn_relu_maxpool, [ 24 ] ],    # 0-P2/4
        [ -1, 1, Shuffle_Block, [ 116, 2 ] ], # 1-P3/8
        [ -1, 3, Shuffle_Block, [ 116, 1 ] ], # 2
        [ -1, 1, Shuffle_Block, [ 232, 2 ] ], # 3-P4/16
        [ -1, 7, Shuffle_Block, [ 232, 1 ] ], # 4
        [ -1, 1, Shuffle_Block, [ 464, 2 ] ], # 5-P5/32
        [ -1, 3, Shuffle_Block, [ 464, 1 ] ], # 6
      ]

    # YOLOv5 head
    head:
      [ [ -1, 1, Conv, [ 128, 1, 1 ] ],
        [ -1, 1, nn.Upsample, [ None, 2, 'nearest' ] ],
        [ [ -1, 4 ], 1, Concat, [ 1 ] ],  # cat backbone P4
        [ -1, 1, C3, [ 128, False ] ],  # 10

        [ -1, 1, Conv, [ 128, 1, 1 ] ],
        [ -1, 1, nn.Upsample, [ None, 2, 'nearest' ] ],
        [ [ -1, 2 ], 1, Concat, [ 1 ] ],  # cat backbone P3
        [ -1, 1, C3, [ 128, False ] ],  # 14 (P3/8-small)

        [ -1, 1, Conv, [ 128, 3, 2 ] ],
        [ [ -1, 11 ], 1, Concat, [ 1 ] ],  # cat head P4
        [ -1, 1, C3, [ 128, False ] ],  # 17 (P4/16-medium)

        [ -1, 1, Conv, [ 128, 3, 2 ] ],
        [ [ -1, 7 ], 1, Concat, [ 1 ] ],  # cat head P5
        [ -1, 1, C3, [ 128, False ] ],  # 20 (P5/32-large)

        [ [ 14, 17, 20 ], 1, Detect, [ nc, anchors ] ],  # Detect(P3, P4, P5)
      ]

  # Don't work
  yolov5_lite_dw:
    nc: 1  # number of classes
    classes: ['nothing']    # modify here -> name of classes

    depth_multiple: 1.0  # model depth multiple
    width_multiple: 1.0  # layer channel multiple

    # anchors
    anchors:
      - [ 4,5,  8,10,  13,16 ]  # P3/8
      - [ 23,29,  43,55,  73,105 ]  # P4/16


    # custom backbone
    backbone:
      # [from, number, module, args]
      [ [ -1, 1, conv_bn_relu_maxpool, [ 24 ] ],    # 0-P2/4
        [ -1, 1, Shuffle_Block, [ 48, 2 ] ], # 1-P3/8
        [ -1, 3, Shuffle_Block, [ 48, 1 ] ], # 2
        [ -1, 1, Shuffle_Block, [ 96, 2 ] ], # 3-P4/16
        [ -1, 7, Shuffle_Block, [ 96, 1 ] ], # 4
        [ -1, 1, Shuffle_Block, [ 192, 2 ] ], # 5-P5/32
        [ -1, 3, Shuffle_Block, [ 192, 1 ] ], # 6
      ]

    # YOLOv5 head
    head:
      [ [ -1, 1, Conv, [ 192, 1, 1 ] ],
        [ -1, 1, nn.Upsample, [ None, 2, 'nearest' ] ],
        [ [ -1, 4 ], 1, ADD, [ 1 ] ],  # cat backbone P4
        [ -1, 1, DWConvblock, [ 192 ] ],  # 10

        [ -1, 1, Conv, [ 96, 1, 1 ] ],
        [ -1, 1, nn.Upsample, [ None, 2, 'nearest' ] ],
        [ [ -1, 2 ], 1, ADD, [ 1 ] ],  # cat backbone P3
        [ -1, 1, DWConvblock, [ 96 ] ],  # 14

        [ [ 14, 10 ], 1, Detect, [ nc, anchors ] ],  # Detect(P3, P4, P5)
      ]

  # Don't work
  yolov5_lite_c3:
    nc: 1  # number of classes
    classes: ['nothing']    # modify here -> name of classes

    depth_multiple: 1.0  # model depth multiple
    width_multiple: 1.0  # layer channel multiple

    # anchors
    anchors:
      - [11,16,  28,27,  33,74,  ]  # P3/8
      - [ 83,61,  107,162,  297,278 ]  # P4/16

    # custom backbone
    backbone:
      # [from, number, module, args]
      [ [ -1, 1, conv_bn_relu_maxpool, [ 24 ] ],    # 0-P2/4
        [ -1, 1, Shuffle_Block, [ 48, 2 ] ], # 1-P3/8
        [ -1, 3, Shuffle_Block, [ 48, 1 ] ], # 2
        [ -1, 1, Shuffle_Block, [ 96, 2 ] ], # 3-P4/16
        [ -1, 7, Shuffle_Block, [ 96, 1 ] ], # 4
        [ -1, 1, Shuffle_Block, [ 192, 2 ] ], # 5-P5/32
        [ -1, 3, Shuffle_Block, [ 192, 1 ] ], # 6
      ]

    # YOLOv5 head
    head:
      [ [ -1, 1, Conv, [ 128, 1, 1 ] ],  # 7
        [ -1, 1, nn.Upsample, [ None, 2, 'nearest' ] ],  # 8
        [ [ -1, 4 ], 1, Concat, [ 1 ] ],  # cat backbone P4  9
        [ -1, 1, Light_C3, [ 128, False ] ],  # 10

        [ -1, 1, Conv, [ 128, 1, 1 ] ],   # 11
        [ -1, 1, nn.Upsample, [ None, 2, 'nearest' ] ],  # 12
        [ [ -1, 2 ], 1, Concat, [ 1 ] ],  # cat backbone P3  # 13
        [ -1, 1, Light_C3, [ 128, False ] ],  # 14 (P3/8-small)

        [ [ 14, 10 ], 1, Detect, [ nc, anchors ] ],  # Detect(P3, P4, P5)
      ]

  yolov5_lite_p4:
    nc: 1  # number of classes
    classes: ['nothing']    # modify here -> name of classes
    
    depth_multiple: 1.0  # model depth multiple
    width_multiple: 1.0  # layer channel multiple

    # anchors
    anchors:
      - [ 4,5,  8,10,  13,16 ]  # P3/8
      - [ 23,29,  43,55,  73,105 ]  # P4/16
      - [ 146,217,  231,300,  335,433 ]  # P5/32

    # custom backbone
    backbone:
      # [from, number, module, args]
      [ [ -1, 1, conv_bn_relu_maxpool, [ 24 ] ],    # 0-P2/4
        [ -1, 1, Shuffle_Block, [ 48, 2 ] ], # 1-P3/8
        [ -1, 3, Shuffle_Block, [ 48, 1 ] ], # 2
        [ -1, 1, Shuffle_Block, [ 96, 2 ] ], # 3-P4/16
        [ -1, 7, Shuffle_Block, [ 96, 1 ] ], # 4
        [ -1, 1, Shuffle_Block, [ 192, 2 ] ], # 5-P5/32
        [ -1, 3, Shuffle_Block, [ 192, 1 ] ], # 6
      ]

    # YOLOv5 head
    head:
      [ [ -1, 1, Conv, [ 64, 1 ] ],
        [ -1, 1, nn.Upsample, [ None, 2, 'nearest' ] ],
        [ [ -1, 4 ], 1, Concat, [ 1 ] ],  # cat backbone P4
        [ -1, 1, C3, [ 64, False ] ],  # 10

        [ -1, 1, Conv, [ 64, 1, 1 ] ],
        [ -1, 1, nn.Upsample, [ None, 2, 'nearest' ] ],
        [ [ -1, 2 ], 1, Concat, [ 1 ] ],  # cat backbone P3
        [ -1, 1, C3, [ 64, False ] ],  # 14 (P3/8-small)

        [ -1, 1, Conv, [ 64, 3, 2 ] ],
        [ [ -1, 11 ], 1, Concat, [ 1 ] ],  # cat head P4
        [ -1, 1, C3, [ 64, False ] ],  # 17 (P4/16-medium)

        [ -1, 1, Conv, [ 64, 3, 2 ] ],
        [ [ -1, 7 ], 1, Concat, [ 1 ] ],  # cat head P5
        [ -1, 1, C3, [ 64, False ] ],  # 20 (P5/32-large)

        [ [ 14, 17, 20 ], 1, Detect, [ nc, anchors ] ],  # Detect(P3, P4, P5)
      ]

  # Don't work
  yolov5_efficient_lite0:
    # parameters
    nc: 1  # number of classes
    classes: ['nothing']    # modify here -> name of classes
    
    depth_multiple: 1.0  # model depth multiple
    width_multiple: 1.0  # layer channel multiple

    # anchors
    anchors:
      - [11,16,  28,27,  33,74,  ]  # P3/8
      - [ 83,61,  107,162,  297,278 ]  # P4/16

    # custom backbone
    backbone:
      # [from, number, module, args]
      [ [ -1, 1, stem, [ 32 ] ],    # 0-P2/4
        [ -1, 1, MBConvBlock, [ 16, 3, 1 ] ], # 1-P3/8
        [ -1, 3, MBConvBlock, [ 24, 3, 2 ] ], # 2
        [ -1, 1, MBConvBlock, [ 40, 5, 2 ] ], # 3-P4/16
        [ -1, 7, MBConvBlock, [ 80, 3, 2 ] ], # 4
        [ -1, 1, MBConvBlock, [ 112, 5, 1 ] ], # 5-P5/32
        [ -1, 3, MBConvBlock, [ 192, 5, 2 ] ], # 6
        [ -1, 3, MBConvBlock, [ 320, 3, 1 ] ], # 7
      ]

    # YOLOv5 head
    head:
      [ [ -1, 1, Conv, [ 128, 1, 1 ] ],
        [ -1, 1, nn.Upsample, [ None, 2, 'nearest' ] ],
        [ [ -1, 4 ], 1, Concat, [ 1 ] ],  # cat backbone P4
        [ -1, 1, C3, [ 128, False ] ],  # 11

        [ -1, 1, Conv, [ 128, 1, 1 ] ],
        [ -1, 1, nn.Upsample, [ None, 2, 'nearest' ] ],
        [ [ -1, 2 ], 1, Concat, [ 1 ] ],  # cat backbone P3
        [ -1, 1, C3, [ 128, False ] ],  # 15 (P3/8-small)

        [ -1, 1, Conv, [ 128, 3, 2 ] ],
        [ [ -1, 11 ], 1, Concat, [ 1 ] ],  # cat head P4
        [ -1, 1, C3, [ 128, False ] ],  # 18 (P4/16-medium)

        [ [ 15, 18 ], 1, Detect, [ nc, anchors ] ],  # Detect(P3, P4, P5)
      ]
###############################################################